# Generated by Django 5.0.7 on 2025-01-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locion',
            new_name='Product',
        ),
    ]
